CgroupMountpoint=/sys/fs/cgroup

# Config the file /etc/slurm/cgroup.conf

CgroupAutomount=yes
# CgroupReleaseAgentDir="/etc/slurm/cgroup"

ConstrainCores=yes
ConstrainDevices=yes
# TaskAffinity=yes
ConstrainRAMSpace=yes
# ConstrainSwapSpace=yes
MaxRAMPercent=95
AllowedSwapSpace=0
AllowedRAMSpace=200
MemorySwappiness=0
