AuthType=auth/munge
DbdAddr=slurmmaster
DbdHost=slurmmaster
DbdPort=6819
SlurmUser=slurm
DebugLevel=4
# log and pid files
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurm/slurmdbd.pid
StorageType=accounting_storage/mysql
StorageHost=slurmmaster
StorageLoc=slurm_acct_db
StoragePass=admin
StorageUser=slurm
# setting database purge parameters
PurgeEventAfter=12months
PurgeJobAfter=12months
PurgeResvAfter=2months
PurgeStepAfter=2months
PurgeSuspendAfter=1month
PurgeTXNAfter=12months
PurgeUsageAfter=12months

