CC=gcc
CFLAGS=-Wall

all: string_preprocess

string_preprocess: string_preprocess.c
	gcc -o string_preprocess string_preprocess.c

run: string_preprocess
	./string_preprocess	

clean:
	rm -f string_preprocess

